# Generated by Django 4.2.1 on 2023-05-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calenBar', '0002_calendar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='color_theme',
        ),
    ]
