# Generated by Django 4.2.1 on 2023-05-15 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calenBar', '0003_remove_calendar_color_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.AddField(
            model_name='task',
            name='goal_end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 0, 0)),
            preserve_default=False,
        ),
    ]
