# Generated by Django 4.2.1 on 2023-05-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calenBar', '0004_remove_task_priority_task_goal_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='event_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
    ]
